# Analysis of Flight data for Indianopolis
myDF <- read.csv('/Users/debmalyajash/git/RACT/data/2008.csv')
head(myDF)
head(myDF$Origin)
tail(myDF$Origin)
head(myDF$Dest)
tail(myDF$Dest)
head(myDF$Origin == 'IND')
sum(myDF$Origin=='SFO')
sum(myDF$Dest=='SFO')
sum(myDF$Origin=='IND')
sum(myDF$Dest=='IND')
sum(myDF$Origin=='ORD')
sum(myDF$Dest=='ORD')
sum((myDF$Origin == "IND") & (myDF$Dest == "ORD"))
myIndyOrigin <- subset(myDF,myDF$Origin == 'IND')
myIndyDesti <- subset(myDF,myDF$Dest == 'IND')
TUP <- subset(myDF,(myDF$Origin == 'TUP') & (myDF$Year=='2008'))
sum((myDF$Origin == 'TUP') & (myDF$Year=='2008'))
sum(TUP$DepDelay)
table(TUP$Month)
table(myIndyOrigin$Month)                  
plot(table(myIndyOrigin$Month) )
sum((myDF$Dest=='LAX') & (myDF$Year=='2008'))
sum((myDF$Origin=='ATL') & (myDF$Dest=='LAX') & (myDF$Year=='2008'))
ATL2008 <- subset(myDF,((myDF$Origin=='ATL') & (myDF$Dest=='LAX') & (myDF$Year=='2008') ))
table(ATL2008$DepTime)
table(ATL2008$DepTime<'1200')
table(ATL2008$DepTime>'1200')
plot(table(ATL2008$DepTime))
sum(ATL2008$DepTime < '1200')
table(ATL2008$ArrTime <'1200')
# This one is important where value na those will be counted as TRUE
sum (ATL2008$DepTime < 1200, na.rm=TRUE)
